### ISSUE TITLE
run demo error

### ISSUE THREAD

**Issue by xiegongsheldon** [kristijanbartol/linear-3d-humans#2]
(LINEENV) (base) xsc@xsc-Precision-3650-Tower:~/workspace/linear3dhumans/linear-3d-humans$ python3 demo.py 
Enter your gender ([male, female]):male
Enter your height [in meters] and weight [in kg]: 1.72 56
Traceback (most recent call last):
  File "demo.py", line 20, in <module>
    meas_coefs = np.load(MEAS_COEF_FILE.format(gender_in))
  File "/home/xsc/workspace/linear3dhumans/LINEENV/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: './results/male_meas_coefs.npy'

**Comment by kristijanbartol** [comment]
I apologize for not including the files and thank you for creating an issue. Please try to rerun the script now.

**Comment by xiegongsheldon** [comment]
> I apologize for not including the files and thank you for creating an issue. Please try to rerun the script now
good works! it can run successfully
